import {
  DEFAULT_MAX_UNDO, DEFAULT_MAP_COLS, DEFAULT_MAP_ROWS, DEFAULT_TILE_OPACITY,
  DEFAULT_TERRAIN_DEFS, DEFAULT_AUTOSAVE_MS, DEFAULT_BUILDING_TYPES
} from './constants.js';

export const state = {
  MAX_UNDO: DEFAULT_MAX_UNDO,
  TERRAIN_DEFS: DEFAULT_TERRAIN_DEFS.map(t => ({ ...t })),
  TERRAIN_COLORS: {},
  mapCols: DEFAULT_MAP_COLS,
  mapRows: DEFAULT_MAP_ROWS,
  hexes: new Map(),
  camera: { x: 0, y: 0, zoom: 1 },
  viewLayers: { terrain: true, elevation: true, ownership: true, regions: true, loyalty: false, controller: false, culture: false, population: false, routes: true, buildings: true, units: true },
  showFullGrid: false,
  tileOpacity: DEFAULT_TILE_OPACITY,
  prefConfirmDeletes: true,
  prefConfirmCleanOcean: true,
  prefWarnUnload: true,
  prefPromptRestore: true,
  prefAllowOceanElevPop: true,
  heatmapScale: 'log',
  popStats: { max: 0, dirty: true },
  activeTool: 'terrain',
  backgroundEditMode: false,
  capitalPickMode: false,
  brush: {
    terrain: 'ocean',
    elevation: 'hills',
    populationMode: 'set',
    populationAmount: 0,
    owner: '',
    regionId: null,
    loyalty: '',
    controller: '',
    culture: '',
    size: 1,
    routeStyle: 'river1',
    pathMode: 'draw',
    buildingTypeId: 'outpost',
    buildingOwnerCode: '',
    buildingName: '',
    unitOwnerCode: '',
    unitName: '',
    unitPersonnel: 1000,
    unitNotes: ''
  },
  buildingTypes: DEFAULT_BUILDING_TYPES.map(t => ({ ...t })),
  nextBuildingSeq: 0,
  routes: [],
  nextRouteId: 1,
  pathDraft: null,
  selectedRouteId: null,
  routeDrag: null,
  bgImage: { img: null, opacity: 0.5, scale: 1, offsetX: 0, offsetY: 0, visible: true },
  isPainting: false,
  isPanning: false,
  isDraggingBg: false,
  lastPanX: 0,
  lastPanY: 0,
  hoveredHex: null,
  selectedHex: null,
  undoStack: [],
  redoStack: [],
  isActionActive: false,
  activeUndoDelta: new Map(),
  activeFactionsBefore: null,
  activeCulturesBefore: null,
  activeRegionsBefore: null,
  autosaveTimerId: null,
  autosaveIntervalMs: DEFAULT_AUTOSAVE_MS,
  lastAutosaveAt: 0,
  factionCounts: null,
  capitalIndex: null,
  routeCellIndex: null,
  factions: new Map(),
  cultures: new Map(),
  regions: new Map(),
  nextRegionId: 1,
  factionDraft: null,
  factionDraftOriginalName: null,
  factionCodeDirty: false
};

state.TERRAIN_DEFS.forEach(t => { state.TERRAIN_COLORS[t.id] = t.color; });

export const hooks = {
  render() {},
  refreshFactionList() {},
  refreshLoyaltyList() {},
  refreshControllerList() {},
  refreshCultureList() {},
  refreshRegionList() {},
  refreshRouteList() {},
  refreshSelectedHexPanel() {},
  refreshPathUi() {},
  refreshInteractionUI() {},
  updateHistoryButtons() {},
  syncRouteSwatches() {},
  syncBgInputs() {},
  updateInspector() {},
  rebuildTerrainColors() {},
  rebuildTerrainSwatches() {},
  syncFactionBrushInputs() {},
  syncRegionBrushInputs() {},
  syncCultureColorInput() {},
  updateToolVisibility() {},
  setActiveTool() {},
  closeFactionEditor() {},
  openModal() {},
  refreshBuildingUi() {}
};

export function bindHooks(next) {
  Object.assign(hooks, next);
}
